//could I just put this in a .json file?
countryData = [
    ["Angola", "AO"],
    ["Benin", "BJ"],
    ["Botswana", "BW"],
    ["Burkina Faso", "BF"],
    ["Burundi", "BI"],
    ["Cameroon", "CM"],
    ["Cape Verde", "CV"],
    ["Central African Republic", "CF"],
    ["Chad", "TD"],
    ["Comoros", "KM"],
    ["Congo", "CG"],
    ["DR Congo", "CD"],
    ["Djibouti", "DJ"],
    ["Egypt", "EG"],
    ["Equatorial Guinea", "GQ"],
    ["Eritrea", "ER"],
    ["eSwatini", "SZ"],
    ["Ethiopia", "ET"],
    ["Gabon", "GA"],
    ["Gambia", "GM"],
    ["Ghana", "GH"],
    ["Guinea", "GN"],
    ["Guinea-Bissau", "GW"],
    ["Ivory Coast", "CI"],
    ["Kenya", "KE"],
    ["Lesotho", "LS"],
    ["Liberia", "LR"],
    ["Libya", "LY"],
    ["Madagascar", "MG"],
    ["Malawi", "MW"],
    ["Mali", "ML"],
    ["Mauritania", "MR"],
    ["Mauritius", "MU"],
    ["Morocco", "MA"],
    ["Mozambique", "MZ"],
    ["Namibia", "NA"],
    ["Niger", "NE"],
    ["Nigeria", "NG"],
    ["Rwanda", "RW"],
    ["Sahrawi*", "SW"],
    ["Sao Tome and Principe", "ST"],
    ["Senegal", "SN"],
    ["Seychelles", "SC"],
    ["Sierra Leone", "SL"],
    ["Somalia", "SO"],
    ["South Africa", "ZA"],
    ["South Sudan", "SS"],
    ["Sudan", "SD"],
    ["Tanzania", "TZ"],
    ["Togo", "TG"],
    ["Tunisia", "TN"],
    ["Uganda", "UG"],
    ["Zambia", "ZM"],
    ["Zimbabwe", "ZW"]
]